import { Inter } from "next/font/google";
import "./globals.css";
import { headers } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export async function generateMetadata() {
  const baseWebUrl = headers().get('host');
  console.log(baseWebUrl)
  const image = 'https://' + baseWebUrl + '/image.png'
  return {
    metadataBase: new URL(image),
    title: "Test APP",
    description: "Despcription",
    openGraph: {
      title: `Message from USER 111`,
      description: "March 13th, 2024 - 9:29pm",
      url: 'test.app',
      siteName: 'test.app',
      images: [
        {
          url: image,
          width: 300,
          height: 150,
          type: 'image/png',
        },
      ],
      type: 'website',
    },
  };
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
